### ISSUE TITLE
hashlet 1.1.0: issueon src/parser/hashlet_bison.y

### ISSUE THREAD

**Issue by ntimeu** [cryptotronix/hashlet#45]
Hello,

After trying to add hashlet to a Yocto build, I found this :

`/home/<name>/<meta>/<meta-name>/build/tmp/work/cortexa9t2hf-neon-see-linux-gnueabi/hashlet/1.1.0-r0/build/../git/src/parser/hashlet_bison.y:40.12-21: warning: POSIX yacc reserves %type to nonterminals [-Wyacc]
   40 | %type<num> KEY_NUMBER
      |            ^~~~~~~~~~

/home/<name>/<meta>/<meta-name>/build/tmp/work/cortexa9t2hf-neon-see-linux-gnueabi/hashlet/1.1.0-r0/build/../git/src/parser/hashlet_bison.y:41.12-14: warning: POSIX yacc reserves %type to nonterminals [-Wyacc]
   41 | %type<hex> HEX
      |            ^~~
`

It seems to be linked to the recent version of bison, which raises a warning when those lines are encountered. (https://savannah.gnu.org/forum/forum.php?forum_id=9639)[See 3.5]

After searching, I found this : (https://www.gnu.org/software/bison/manual/html_node/Type-Decl.html)[Type-Decl]; I used this to replace %type declarations with %nterm, but It seems that the build system is expecting us to be compatible with Yacc.

Do you have any idea how to fix this bison issue ?

**Comment by jbdatko** [comment]
Short answer: I have no idea.

Longer answer: I should archive this repo. It's a nice little project, but I picked some odd libraries (like an old libgcrypt) and I was was really into flex and bison when I should have used something more standard.

If you are using this for anything non-hobby you'll have a better time using the now official Microchip library (this didn't exist when I wrote hashlet) https://github.com/MicrochipTech/cryptoauthlib

Admittedly, the thing that most people like about hashlet is it "just works" (when it does :P) cryptoauthlib you have to do some of this work yourself, but it is otherwise, well supported.

**Comment by ntimeu** [comment]
Hi @jbdatko and thanks for the answer.

We are still trying to make it work. I will look at the cryptoauthlib, but as you pointed out, the "it just work" effect is why we are trying to make it work ^^

And maybe if we have more time we will use the cryptoauthlib.
